### PR TITLE
Fix #610 Fetch revisions by objectId and schemaName

### LINKED ISSUE #610: Fetch revision of data agreement by filtering data agreement id and schema name
Currently filtering using data agreement id, it needs to be updated because same id can be used for data agreement and policy

### PR DESCRIPTION
**Pull request by albinpa**

### CODE REVIEW

**Review by georgepadayatti — CHANGES_REQUESTED** [review]
Can we split this PR into 13 commits - https://github.com/decentralised-dataexchange/bb-consent-api/issues/610#issuecomment-1877012144. This is too big a PR for me to review and approve.

**Comment by albinpa** [comment]
> Can we split this PR into 13 commits - [#610 (comment)](https://github.com/decentralised-dataexchange/bb-consent-api/issues/610#issuecomment-1877012144). This is too big a PR for me to review and approve.

Ok.

**Comment by georgepadayatti** [comment]
Can you share instructions to run the test suite to test the changes ?

**Comment by albinpa** [comment]
> Can you share instructions to run the test suite to test the changes ?

Yes.

1. Make deployable docker image from `main` branch of `bb-consent-api` by executing `make build/docker/deployable` command
2. Copy image name and paste it in `image` fields value under `api` in `test-docker-compose.yaml` file inside test folder in bb-consent-playground
3. Execute the following commands in `bb-consent-playground`
4. `make destroy`
5. `make build-fixtures`
6. `make build-test`
7. `make setup-test`
8. `make run-test-behave`
9. Make deployable docker image from `fix/610` branch by executing `make build/docker/deployable` command in fix/610 branch
10. Copy image name and paste it in `image` fields value under `api` in `test-docker-compose.yaml` file inside test folder in bb-consent-playground
11. Execute the following commands in `bb-consent-playground`
12. `make destroy`
13. `make setup-test`
14. `make run-test-behave`

**Comment by georgepadayatti** [comment]
Tests have passed

**Review by georgepadayatti — APPROVED** [review]

**Pull request merged**
